### ISSUE TITLE
indentation

### ISSUE THREAD

**Issue by gdedi001** [anjiB72/colmar-academy#2]
When writing HTML, make sure to properly indent child tags accordingly. For example..
https://github.com/anjiB72/colmar-academy/blob/master/index.html#L38-L42

```
<!-- ICON MENU FOR SMALLER SCREENS-->
 <ul class="flex-row" id="menu-mobile" role="presentation">
       <span><li><a href=#><img src="./resources/images/ic-on-campus.svg"></a></li></span>
       <span><li><a href=#><img src="./resources/images/ic-online.svg"></a></li></span>
       <span><li><a href=#><img src="./resources/images/ic-login.svg"></a></li></span>
  </ul>
</nav>

**Comment by anjiB72** [comment]
Thanks for the feedback, I did notice that whilst the indentation looks fine in Atom when I wrote it,  pushing it into Github seems to have removed some of that formatting.     I'm fine with your feedback as it is worth remembering anyway but just something to perhaps be aware of?

**Comment by gdedi001** [comment]
Good point, this has actually happened to me as well. I'm not actually sure why it happens though. With that being said, I went ahead and added another issue (declaration order) for you to take into consideration. Thanks for reaching out!
